// --------------- Website -------------

POST http://localhost:5000/api/website
Content-Type: application/json

{
    "Domain": "https://phongvu.vn/",
    "Icon": "https://phongvu.vn/phongvu/favicon-32x32.png"
}

###
POST http://localhost:5000/api/website
Content-Type: application/json

{
    "Domain": "fptshop.com.vn",
    "Icon": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0GEt9Uh2dAhwcz8tsqDZXnPmtg2BhHbiA1vcB-bn85w&s"
}

###
POST http://localhost:5000/api/website
Content-Type: application/json

{
    "Domain": "thegioididong.com"
}


###
POST http://localhost:5000/api/website
Content-Type: application/json

{
    "Domain": "https://websosanh.vn/"
}

###
GET http://localhost:5000/api/website

### 
GET  http://localhost:5000/api/website/644f95a3949d740316e84291


//--------------------- Category --------------------
###
POST  http://localhost:5000/api/category
Content-Type: application/json

 {
    "Name" : "Asus TUF Gaming FX506LHB HN188W - Intel Core I5 10300H | 8GB | .....",
    "Type":  "Laptop",
    "Price": 1000,
    "Imgs": ["http://localhost:5000/api/website/644b319a521f62a7eec4531a"],
    "Desc": "Màn hình: 15.6 inch, 1920 x 1080 Pixels, IPS, 144 Hz, Anti-glare LED-backlit\nCPU: Intel, Core i5, 10300H\nRAM: 8 GB (1 thanh 8 GB), DDR4, 2933 MHz"
}

###
GET http://localhost:5000/api/category

###
GET http://localhost:5000/api/category/6450787e949d740316500b00

###
DELETE http://localhost:5000/api/category/644fd12f949d740316036c21

###
GET http://localhost:5000/api/category?quantity=2&name=i3



// ---------------------------- Product ----------------------
###
POST http://localhost:5000/api/product
Content-Type: application/json

{
    "Url": "https://www.thegioididong.com/laptop/asus-tuf-gaming-fx506lhb-i5-hn188w",
    "Name": "Laptop Asus TUF Gaming F15 FX506LHB i5 10300H/8GB/512GB/4GB GTX1650/144Hz/Win11 (HN188W)",
    "Price": 50000,
    "OriginalPrice": 2099000,
    "NameCategory": "Laptop Asus TUF Gaming FX506LHB HN188W - Intel Core I5 10300H | 8GB | .....",
    "Imgs": ["https://cdn.tgdd.vn/Products/Images/44/279259/Slider/vi-vn-asus-tuf-gaming-fx506lhb-i5-hn188w-1.jpg","https://cdn.tgdd.vn/Products/Images/44/279259/Slider/vi-vn-asus-tuf-gaming-fx506lhb-i5-hn188w-2.jpg"]
}

###
POST http://localhost:5000/api/product
Content-Type: application/json

{
    "Url": "https://fptshop.com.vn/may-tinh-xach-tay/asus-tuf-gaming-fx506lhb-hn188w-i5-10300h",
    "Name": "Laptop Asus TUF Gaming FX506LHB-HN188W i5 10300H/8GB/512GB/15.6FHD/GeForce GTX 1650 4GB/Win11",
    "Price": 15990000,
    "OriginalPrice": 2099000,
    "NameCategory": "Laptop Asus TUF Gaming FX506LHB HN188W",
    "Imgs": ["https://images.fpt.shop/unsafe/filters:quality(90)/fptshop.com.vn/Uploads/images/2015/0511/ASUS-TUF-Gaming-F15-2021-black-fpt-3.jpg","https://images.fpt.shop/unsafe/filters:quality(90)/fptshop.com.vn/Uploads/images/2015/0511/ASUS-TUF-Gaming-F15-2021-black-fpt-1.jpg"],
    "Desc": "Màn hình: 15.6 inch, 1920 x 1080 Pixels, IPS, 144 Hz, Anti-glare LED-backlit\nCPU: Intel, Core i5, 10300H\nRAM: 8 GB (1 thanh 8 GB), DDR4, 2933 MHz"
}

###
GET http://localhost:5000/api/product?quantity=2


###
GET http://localhost:5000/api/product/64507753ed8ee8d7430af542

###
GET http://localhost:5000/api/category/644b344f9ed275fa7faec454

###
DELETE http://localhost:5000/api/category/644b344f9ed275fa7faec454

------------------------------------------------
###
DELETE http://localhost:5000/api/category?all=true
###
DELETE https://mmt-main-dbserver.vercel.app/api/product?all=true